### ISSUE TITLE
Request for a config file

### ISSUE THREAD

**Issue by anoomolu** [Pepperoni-Jabroni/PigsHaveLitters#1]
Hiya, this is another one of your mods that I almost can't play without haha, thank you for making it! 

I'm making a personal modpack and was wondering if it'd be possible to introduce a config file so players can set their own litter size proportions. My use case would be setting litter size 2 to 60%, 3 = 30% and 4 = 10%.

**Comment by Pepperoni-Jabroni** [comment]
Thanks for filing a suggestion! This is definitely something I can do. I was also thinking of adding an optional multiplier or alt distribution for pigs bred on mud too!

**Comment by Pepperoni-Jabroni** [comment]
Completed in 1.20.4 version
